### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#10]
Hi,

I switched to new master branch and some examples I have and all test in test.py seem to be failing. They break at the rosetta step, with error messages like

```
File: /home/benchmark/rosetta/source/src/core/chemical/ResidueType.cc:2135
[ ERROR ] UtilityExitException
ERROR: One or more internal errors have occurred in residue type setup for LIG (LIG, Z)
In chi #7, the base of the fourth atom ( O2 ) is  C13, rather than the third atom of the chi ( C10)
In chi #9, the base of the third atom ( O2 ) is  C13, rather than the second atom of the chi ( C10)
In chi #9, the base of the fourth atom ( C13) is  C12, rather than the third atom of the chi ( O2 )


```

**Comment by matteoferla** [comment]
Yes, could you update `rdkit_to_params`? It used to have an issue with ring atoms and &chi; angles but it got fixed and the hack removed.

          pip3 install rdkit_to_params --upgrade

**Comment by rsanchezgarc** [comment]
Solved! Thanks

I am closing this issue
