### ISSUE TITLE
pip install problems

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#11]
It seems that pip install is not working properly as when trying execution, it complains some modules not found.
If you do ```ls lib/python/site-packaged/fragmenstein ```,  some folders/files are missing.

**Comment by matteoferla** [comment]
Damn. To clean up the messy setup.py I had used PyCharm's autogenerated setup.py for all three modules, which switched `find_packages` to just the package name, which does not find subpackages. I have fixed it both GitHub and pypi.

Sorry for delay. I did not realise this was what you meant and clicked only after creating a new virtual environment on my laptop which required space to be freed etc. etc.

**Comment by matteoferla** [comment]
Also, I had setup auto pip on release action, but I had the check for RDKit raise an error, which prevent the action from working, it has been changed to a warning —very dangerous, but rdkit cannot be in requirements.
