### ISSUE TITLE
Should we have a devel branch?

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#2]
I think it will be good practise to make the code more stable to have a devel branch  and leave the master branch untouched until major changes ready.

**Comment by matteoferla** [comment]
Totally. I'll make myself a personal dev branch. This would also permit safe automated GitHub action for pip releases.
BTW. I was midway through doing the tidy-up of Monster to allow Victor to test multiple monster compounds in case of ambiguity.

**Comment by rsanchezgarc** [comment]
Great! Would you like to have

 Master -> Devel -> Devel Matteo
                            -> Devel Ruben 

scheme? Or do you want to skip the Devel in the middle.

Great to know about Monster update!
