### ISSUE TITLE
ligand - setting up Igor: runs for ever

### ISSUE THREAD

**Issue by haroldgrosjean** [matteoferla/Fragmenstein#22]
Hello,

I am trying to fit a merge between 2 fragments in the following way:

```
from rdkit import Chem
import pyrosetta
pyrosetta.init(
extra_options='-no_optH false -mute all -ex1 -ex2 -ignore_unrecognized_res false -load_PDB_components false -ignore_waters false')
from fragmenstein import Victor
import logging
Victor.enable_stdout(level=logging.DEBUG)

hit_F95 = Chem.SDMolSupplier('./F95.sdf')[0]
hit_F584 = Chem.SDMolSupplier('./F584.sdf')[0]

F95_F584 = 'COC1=CC=CC2=C1CC[C@H](NC2=O)C1=CC=C(C=C1)S(N)(=O)=O'

Victor.work_path = './'
victor = Victor(hits=[hit_F95, hit_F584], pdb_filename='./protein_protonated.pdb')
victor.place(F95_F584)
```

```
versions:
rdkit: 2021.09.3
fragmenstein: 0.5
pyrosetta: 2021.52+release.fad969a 

OS: Ubuntu 18.04.6 LTS
```
you may find attached the files required to reproduce the situation here: 
[reproduce.zip](https://github.com/matteoferla/Fragmenstein/files/8639436/reproduce.zip)

Then the software remains stuck on `DEBUG - ligand - setting up Igor` forever but the core is running at 100% cpu capacity. I am unsure what causes the issue and would be grateful if you could help me troubleshooting this.

Many thanks in advance,

Harold

**Comment by matteoferla** [comment]
Even with Fragmenstein version 0.8 and March 2022 Pyrosetta I get the same. Whereas `.combine` gives a molecule with an extra carbon in the bridge, which is strained. However, there's the issue that the placement seems to be all wrong. There is no discard (`victor.monster_throw_on_discard = True` does not trigger).
The `👾👾👾.positioned.mol` file is a mess. I had assumed the amide of F_95 was being disruptive and Fragmenstein fails.
But removing F_95 entires makes a mess anyway, so something is not right with the mapping of the 7-membered lactam
Weirder still flipping the order of the hits (which has an effect in the choice) and/or `AllChem.DeleteSubstructs(hit_F95, Chem.MolFromSmiles('CC(=O)N'))` causes a weird error. So I need to look into this more, but it may be a code fix.

**Comment by haroldgrosjean** [comment]
Hi Matteo,

Many thanks for looking into this.

Bests,

Harold

**Comment by matteoferla** [comment]
###Facepalm time 🤦 
I have been combing through the code, commenting it and dissecting it as I had assumed it was a mapping issue.
I even went through tenuous cause like the flipped amide in the lactam, the chiral hydrogen or the wonky overlap of the methylamide and lactam...

Well it turns out that SDF files has the same name on their hits `MOL`, which `Monster.fix_hits` does not address.
Such an obvious issue, but I had never thought of it  🤡.

```python
hit_F95 = Chem.SDMolSupplier('../files_bug/F95.sdf')[0]
hit_F95.SetProp('_Name', 'hit_F95')
hit_F584 = Chem.SDMolSupplier('../files_bug/F584.sdf')[0]
hit_F584.SetProp('_Name', 'hit_F584')
```
