### ISSUE TITLE
Questions regarding covalent_resi in Victor

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#3]
I have a few questions regarding covalent_resi in Victor's builder.

I though it was only required for covalent hits (those that contained a * in the smiles), but I tried to create an instance of Victor using the smile 'Cc1ccncc1NC(=O)Cc1cccc(Cl)c1', the hits 'x0107' ,'x0434', 'x1382'  and the template pdb from the MPro, with no covalent_resi,  and it failed (as it is done in MProVictor). Rosetta complains about bad residue number 

` 
Constraint file specified to constrain using Pose residue 0. That cannot be possible! Rosetta numbering starts at 1
`
The error disappears when, line in MProVictor, I set the covalent_resi to 81A

So the question is, why do we need this parameters for no covalent hits?  wouln't It be as easy as picking a random residue instead for non-covalent hits? Or, is there something special with the 81A residue? If so, how do you pick it?

**Comment by matteoferla** [comment]
You are correct there. There is nothing special. In the case of a non-covalent ligand, the atom is used as a reference for the restraints (the absolute xyz coordinate space is a hoax, it's a relative affair). It was coded as if non-covalent ligands were uncommon. I should change it so it picks the closest CA or even the just the first.
