### ISSUE TITLE
Continuous warning about Hs

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#31]
Hi, every time I am using Igor I got this warning
[14:56:15] Molecule does not have explicit Hs. Consider calling AddHs()

**Comment by matteoferla** [comment]
Victor.capture_logs() stopped capturing, so switched to LogToPythonLogger.

This is however enabled when logging is interfered with:

* `Victor.enable_stdout(logging.CRITICAL)` — affects all logs
* `Victor.capture_logs()` — affects Rosetta and rdkit logs
* `Victor.capture_rdkit_log()` — rdkit only
