### ISSUE TITLE
AtomicRenamer superseded by Fragmenstein

### ISSUE THREAD

**Issue by noahharrison64** [matteoferla/Fragmenstein#38]
Hi,

I've just started using AtomicRenamer and noticed on the repo that it says this module supersedes it. I was wondering if there are any updates to the AtomicRenamer module inside Fragmenstein (i.e. if it's worth using this module just for the purpose of the renamer), and if so, how to access the renamer functionality?

The reason I ask is because when trying to use AtomicRenamer, while it works on a significant number of PDBs and their ligands, it fails on 6wtn and its cognate ligand RXT, raising the assertion error:
`"the number of atoms in mol has to be the same as atomlabels. Hydrogens? dehydrogenate!"
`
The mol I'm providing as input is as follows:
`'c1c[nH]c2c1c(ncn2)c3cnn(c3)C(CC#N)C4CCCC4'`

Any suggestions for how to fix would be greatly appreciated!
Thanks,
Noah

**Comment by matteoferla** [comment]
It is a re-write basically, but majorly Fragmenstein does a lot more and uses PyRosetta (molecular thermodynamics), which is like using a sledgehammer to crush a walnut.

In your case I am guessing `c1c[n-]c2c1c(ncn2)c3cnn(c3)C(CC#N)C4CCCC4` will be tolerated.
