### ISSUE TITLE
Problems with warheads

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#4]
I am trying to apply Victor.combine over the hits 'x0104', 'x1458' and I am getting the following error:

`
ERROR:Fragmenstein:x0104-x1458 — ValueError: x0104-x1458 - Unsure what the warhead is CC(=O)NCCC1=C2C=C(F)C=CC2N=C1.
`
The smiles of the hits are:
`
['CC(=O)NCCc1c[nH]c2ccc(F)cc12', '*CC(=O)N1CCC(C(=O)N(C)C(C)C)CC1']
`

I guess that what it happens is that it rules out the second fragment, which is the covalent one. Is there any way to force it to link them no matter how bad the linker is ?

**Comment by matteoferla** [comment]
I had written [something about covalent residues](https://github.com/matteoferla/Fragmenstein/blob/dev-teo/documentation/covalents.md).

I am not sure why `Victor.combine` is even attempting a warhead conversion. Even if it were `CC(=O)NCCC1=C2C=C(F)C=CC2N=C1` is not a reactive compound (`ClCC(=O)..` or `C=CC(=O)..` are). So I am glad you got to the bottom of it.

I should stress though that there is a reason why the warhead definition is `*CC(=O)` as opposed to `*CC(=O)N` —I thought I saw a msg about it. This is to allow the nitrogen to become a tertiary amine without being stopped for wanting to modify a warhead. Also, say the conversion of `ClCC(=O)N(C)C` to `*CC(=O)N(C)C` causes drama regardless of how clean the SMART string is.  It's simpler just making way `ClCC(=O)` the warhead.
Furthermore, the nitrogen is not involved in any bonding so optional restrains aren't called for.
