### ISSUE TITLE
rdkit / pandas version broken

### ISSUE THREAD

**Issue by james-vincent** [matteoferla/Fragmenstein#47]
Pandas 2.2.0 made changes that break in rdkit:

https://github.com/rdkit/rdkit/pull/7165

This happens with versions currently specified in environment.yml:

fragmenstein/igor/pyrosetta_import.py:38: RuntimeWarning: PyRosetta is not installed. A mock object is loaded. Any Igor calls will fail.
  warnings.warn('PyRosetta is not installed. A mock object is loaded. Any Igor calls will fail.',
Failed to find the pandas get_adjustment() function to patch
Failed to patch pandas - PandasTools will have limited functionality
usage: fragmenstein [-h] {monster,laboratory,pipeline,victor,utils} ...

**Comment by matteoferla** [comment]
Thanks. I did notice that. RDKit `2023.9.6` is out next month so for now I have done a patch
