### ISSUE TITLE
Multiple possibilities of merged hits. 

### ISSUE THREAD

**Issue by HaotianZhangAI4Science** [matteoferla/Fragmenstein#48]
Dear sir, 

    It's a good work! I have some additional results about whether can we get the multiple results of merged ligands. For example, I run the following example code:

        victor = Victor(hits=[hit_1, hit_2], pdb_filename='./example/1d7j_A_rec.pdb')
        victor.combine()

    The result mol is always the same. I think it would be great if fragmenstein can generate multiple choices! 

Best, 
Odin

**Comment by matteoferla** [comment]
This is something that has popped up a few times in discussions, but unfortunately is not possible to make it sample _nicely_.

It is partially deterministic —the seed might change results slightly, but not by much.
The order of the parent hits matters, so **shuffling the parent hits** gives a different result (for example a superposed furan and benzene will give furan, a superposed benzene and furan will give benzene.
If the hits are large (or with parts that are topologically confusing) then I generally **decompose and do three or more way mergers**.

Adding noise to the parent hit coordinates can change the results, but goes quickly from no-change to an synthetic-accessibility nightmare.

Given that most users rely on catalogues, the diversity happens at the analogue enumeration anyway.
If a CRO or in-house synthesis is being used then yes, the diversity would be handy as one could run it through Manifold or AIZynthFinder or eyeball in. But most likely a guess on synthetic chemistry strategy would happen anyway as nobody would want to fullfill an order for a plate requiring say sulfo-Schotten–Baumann for well A1, aza-Diels-Alders for well A2, Suzuki for A3 etc. so it would boil down to enumerating scaffold analogues again.

In Fragmenstein synthetic accessibility is a result of the parent hits —the rectification fixes weird chemistry, but doesn't directly tackle SA. As a result it underperforms with natural products say.
I have been thinking of how one could address it, but would require a completely different algorithm.
Furthermore, to complicate matters with compound enumeration of analogue-catalogues, there's still the need to go through the results one-by-one as things like say a nitroso, amidine, fmoc, isoxazole or chloracetamide are real SA'able groups, but are for special occasions.

**Comment by HaotianZhangAI4Science** [comment]
Thanks for your patient response! I got it.

**Comment by matteoferla** [comment]
Not a problem: the opposite
