### ISSUE TITLE
Wictor Atom.SetProp() Error

### ISSUE THREAD

**Issue by kate-fie** [matteoferla/Fragmenstein#52]
Versions:

```python
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
on Linux x86_64
with Fragmenstein 1.0.4 and PyRosetta  2024.16+release.bc4dfa1
```

I'm curently using Wictor to place merged compounds with a timeout of 800 and not seeing any successful minimisation due to this error:
```python
ArgumentError: Python argument types in
    Atom.SetProp(Atom, str, int)
did not match C++ signature:
    SetProp(RDKit::Atom const* self, char const* key, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > val)
```
I saw this error as well with `Fragmenstein 1.0.3`.

All code to reproduce this is found [here](https://github.com/kate-fie/EV-A71-2A-syndirella-run/tree/975f6142e05eb05f999a04bfe642537eb9eafac9/repeat_placements_april22). Where the script for placement is [run_place.py](https://github.com/kate-fie/EV-A71-2A-syndirella-run/blob/eb9b70cb23cf57f072e11fcfb6d39ad3529bad0f/repeat_placements_april22/run_place.py). Thanks for your help!

**Comment by matteoferla** [comment]
Thank you for providing an example. Unfortunately on my system it does not crash but gives a result. Given for 1.0.3 I blindly forced all SetProp values, I suspect the issue is a dependency.  Could you try `pip install rdkit==2023.09.5 rdkit-to-params==1.2.8 molecular-rectifier==1.0.1 `

**Comment by kate-fie** [comment]
Installing these exact package versions fixed the issue! 

> `pip install rdkit==2023.09.5 rdkit-to-params==1.2.8 molecular-rectifier==1.0.1 `

Now minimisations are successful.
