### ISSUE TITLE
Import pyrosetta within classes instead global scope

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#6]
Now, pyrosetta is imported at the beginning of the files. If imported within class, import would be delayed till really needed, speeding up importing of the whole package.

**Comment by matteoferla** [comment]
Sorry for being slow,  but I don't quite follow what the advantage is and I am not sure why the import time is problematic: on my MacBook it takes 2.5 second to import `pyrosetta`, which is a lot for an import, but in human terms it is nothing.

If you are asking that pyrosetta be imported only when Igor is used, then I am pretty sure importing `from fragmenstein.monster import Monster` would circumvent that anyway as `fragmenstein.__init__` is not run.

The pyrosetta module is also used for typehinting, which would mean that a`typing.TYPE_CHECKING` if-block would be required on each Igor file, which is messier.

If imported at the class level

    class Foo:
          import bar
          def baz(self):
                 self.bar.module_fxn()

`bar` would still be imported when importing the class `Foo`.  Unless it is imported at instantiation. In which case it would need to be either attached to the instance or re-imported when needed.

**Comment by rsanchezgarc** [comment]
First of all, sorry for my lack of explanations.

The problem I faced is that, when doing multiprocessing, each time that a worker is created, the whole thing  is imported and if you are creating small tasks, this could have an impact in performance (apart from the annoying warning message that I see when a subprocess is created 'Warning: use "from pymol import cmd" instead of "import cmd"'). And the funny thing is that non of my tasks are using Igor but still  the "import pyrosseta" is reached.
This is a consequence of Igor being imported in the fragmenstein/__init__.py (and the other classes that also import pyrosetta)

Is this a terrible problem? It is not, but I though we could try to figure out how to do it better. But if you thing it is something we should not care, I will just rewrite the parallel code to make it more efficient.

The way I was thinking of was something like:

```
def get_pyRosseta(): 
  import pyrosetta; 
  return pyrosetta


class Foo:
      def do(self):
             get_pyRosseta().doRosetta()
```
but type checking complicate things, since we cannot execute get_pyRosseta at the begining.

**Comment by matteoferla** [comment]
I just checked and I was wrong `__init__` is loaded in an `from foo.bar import bar` case.

For now a quick hack can be is to fake the module pyrosetta, before loading fragmenstein:
 
  import sys
  sys.modules['pyrosetta'] = None
  import pyrosetta #ModuleNotFoundError

In `fragmenstein.__init__`, Igor is optionally loaded as its inside a catch statement for an `ImportError` and the `ModuleNotFoundError.__mro__` is `(ModuleNotFoundError, ImportError, Exception, BaseException, object)`.

`"from pymol import cmd" instead of "import cmd"`? Is that with filter turned on? And logging not capturing warnings? But PyMol for sure can imported with the relevant method. `sys.modules['pymol2']` will be fine too IIRC.

For the longer term, how about having a flag in main namespace to prevent the import of pyrosetta?

**Comment by rsanchezgarc** [comment]
Thanks for the suggestion.
```
import sys
sys.modules['pyrosetta'] = None
import pyrosetta #ModuleNotFoundError
```
I will use it for now.

"from pymol import cmd" instead of "import cmd" comes from pyrosetta. Correct me if I am wrong, but don't I need to import Victor first in order to be able to mess with logging? When importing Victor, you got pyrosetta loaded and the messege pops.

I agree that an environmental variable could be an elegant solution.

**Comment by matteoferla** [comment]
Ops. I need to use this hack for a test and it turns out if the value of `sys.modules` item is None it counts it as deleted.
Then the typehinting (`pyrosetta.Pose`) crashes it. So I did this heinous hack to mock pyrosetta:

```python3
class AttributeFilledMock:
    """
    This allows:
    
    mock = AttributeFilledMock()
    mock.me
    mock.me.again.over()
    """
    def __getattr__(self, attr:str):
        return self
    
    def __call__(self, *args, **kargs):
        return self    
    
pyrosetta = AttributeFilledMock()
sys.modules['pyrosetta'] = pyrosetta```

**Comment by matteoferla** [comment]
I fixed it by making a mock import as discussed as opposed to using the standard way:

```python3
from __future__ import annotations
from typing import *
if TYPE_CHECKING:
     import pyrosetta

def do_pyrosetta_operation() -> pyrosetta.Pose:
       import pyrosetta
        return pyrosetta.Pose()
```
as there may be some corner case where an über-unstable instantiated Igor is useful...
